### ISSUE TITLE
numero 15: 

### ISSUE THREAD

**Issue by ivythegreenest** [sertdfyguhi/meth#1]
walter white
![image](https://github.com/sertdfyguhi/meth/assets/117580169/3444f4f8-a924-4fd1-bcfe-0bc6cbd6f260)

anyways How to define Vari ables???

Help me

**Comment by sertdfyguhi** [comment]
```py
import meth

evaluator = meth.Evaluator()
evaluator.evaluate("x = 5")
# OR
evaluator.set_var("x", 5)
```
walter
